# Generated by Django 4.2.9 on 2026-01-16 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(max_length=100, unique=True)),
                ('inspection_date', models.DateField()),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('inspector_name', models.CharField(max_length=200)),
                ('inspector_license', models.CharField(blank=True, max_length=100)),
                ('workplace_name', models.CharField(blank=True, max_length=200)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('site', models.CharField(blank=True, help_text='SUB FAB, etc.', max_length=200)),
                ('fab', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Complete inspection data in JSON format')),
                ('defects_description', models.TextField(blank=True, help_text='תיאור ליקויים')),
                ('no_defects_note', models.TextField(blank=True, help_text='אין ליקויים - הערות')),
                ('repairs_required', models.TextField(blank=True, help_text='תיקונים נדרשים')),
                ('general_notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='inspection_reports/pdf/')),
                ('source_scan', models.FileField(blank=True, help_text='Original scanned document', null=True, upload_to='inspection_reports/scans/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('final', 'Final')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='equipment.equipment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Report',
                'verbose_name_plural': 'Inspection Reports',
                'db_table': 'inspection_reports',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(choices=[('annual', 'Annual'), ('periodic', 'Periodic'), ('post_repair', 'Post Repair'), ('pre_operation', 'Pre-Operation')], max_length=50)),
                ('inspection_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('inspector_name', models.CharField(max_length=200)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='equipment.equipment')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_inspections', to='inspections.inspectionreport')),
            ],
            options={
                'db_table': 'inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(help_text='Line number in the table')),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('manufacture_year', models.IntegerField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('equipment_number', models.CharField(blank=True, max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('pressure', models.CharField(blank=True, max_length=100)),
                ('volume', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=100)),
                ('condition', models.TextField(blank=True, help_text='Condition notes')),
                ('passed', models.BooleanField(default=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspectionreport')),
            ],
            options={
                'db_table': 'inspection_report_items',
                'ordering': ['report', 'line_no'],
                'unique_together': {('report', 'line_no')},
            },
        ),
        migrations.AddIndex(
            model_name='inspectionreport',
            index=models.Index(fields=['report_number'], name='inspection__report__c983e8_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionreport',
            index=models.Index(fields=['inspection_date'], name='inspection__inspect_62534b_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionreport',
            index=models.Index(fields=['status'], name='inspection__status_747ba8_idx'),
        ),
    ]
