# Generated by Django 4.2.9 on 2026-01-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='fab',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_license',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspection',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='site',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='working_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='workplace_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
