# Generated by Django 4.2.9 on 2026-01-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_cost_inspection_employer_inspection_fab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='attachment',
            field=models.FileField(blank=True, help_text='Inspection attachment or photo', null=True, upload_to='inspections/attachments/'),
        ),
    ]
