# Generated by Django 4.2.9 on 2026-03-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('inspections', '0003_inspection_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='tenants.company'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='defects_description',
            field=models.TextField(blank=True, help_text='תאור ליקויים'),
        ),
    ]
