# Generated by Django 4.2.9 on 2026-03-11 11:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='שם חברה')),
                ('legal_name', models.CharField(blank=True, max_length=300, verbose_name='שם משפטי')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='ח.פ.')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='תעשייה')),
                ('logo', models.ImageField(blank=True, upload_to='companies/logos/', verbose_name='לוגו')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='תוכנית')),
                ('max_equipment', models.IntegerField(default=50, verbose_name='מקסימום ציוד')),
                ('max_users', models.IntegerField(default=3, verbose_name='מקסימום משתמשים')),
                ('max_sites', models.IntegerField(default=1, verbose_name='מקסימום אתרים')),
                ('max_storage_bytes', models.BigIntegerField(default=1073741824, verbose_name='אחסון מקסימלי (בייט)')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל ליצירת קשר')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='טלפון')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='אתר')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('equipment_count', 'Equipment Count'), ('user_count', 'User Count'), ('site_count', 'Site Count'), ('storage_bytes', 'Storage Bytes'), ('api_calls', 'API Calls')], max_length=50)),
                ('value', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='tenants.company')),
            ],
            options={
                'db_table': 'usage_records',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['company', 'metric', '-recorded_at'], name='usage_recor_company_0a7b0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='שם אתר')),
                ('address', models.TextField(blank=True, verbose_name='כתובת')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='עיר')),
                ('district', models.CharField(blank=True, max_length=200, verbose_name='מחוז')),
                ('country', models.CharField(default='Israel', max_length=100, verbose_name='מדינה')),
                ('coordinates', models.JSONField(blank=True, null=True, verbose_name='קואורדינטות')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='איש קשר')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='טלפון')),
                ('floor_plan', models.FileField(blank=True, upload_to='sites/plans/', verbose_name='תוכנית קומה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'sites',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'name'], name='sites_company_c1f2ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('role', models.CharField(default='viewer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.company')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='invitations_token_5b330c_idx'), models.Index(fields=['company', 'status'], name='invitations_company_978be6_idx'), models.Index(fields=['email'], name='invitations_email_6e7169_idx')],
            },
        ),
    ]
