# Generated by Django 4.2.9 on 2026-01-16 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_number', models.CharField(max_length=100, unique=True, verbose_name='Equipment Number')),
                ('equipment_type', models.CharField(choices=[('crane', 'Crane'), ('hoist', 'Hoist'), ('forklift', 'Forklift'), ('elevator', 'Elevator'), ('platform', 'Platform'), ('other', 'Other')], max_length=50)),
                ('manufacturer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('manufacture_year', models.IntegerField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Capacity in tons/kg', max_digits=10, null=True)),
                ('capacity_unit', models.CharField(default='kg', max_length=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters', max_digits=10, null=True)),
                ('working_pressure', models.DecimalField(blank=True, decimal_places=2, help_text='Working pressure', max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('site_name', models.CharField(blank=True, help_text='Site/Location name', max_length=200)),
                ('workplace_name', models.CharField(blank=True, max_length=200)),
                ('employer', models.CharField(blank=True, help_text='Employer/Owner', max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('location_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='equipment.equipment')),
            ],
            options={
                'db_table': 'equipment_specifications',
                'unique_together': {('equipment', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_number'], name='equipment_equipme_786e70_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='equipment_serial__ac559e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_status_92035a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type'], name='equipment_equipme_f4cc15_idx'),
        ),
    ]
