# Generated by Django 4.2.9 on 2026-01-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipment',
            name='equipment_serial__ac559e_idx',
        ),
        migrations.AddField(
            model_name='equipment',
            name='inspector_name',
            field=models.CharField(blank=True, help_text='Inspector name', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
