# Generated by Django 4.2.9 on 2026-03-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_equipment_serial__ac559e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='כתובת'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='building',
            field=models.CharField(blank=True, max_length=200, verbose_name='מבנה / מתקן'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='campus',
            field=models.CharField(blank=True, max_length=200, verbose_name='קמפוס'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='certified_workers',
            field=models.TextField(blank=True, verbose_name='עובדים מוסמכים'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='עיר / יישוב'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='מדינה'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='district',
            field=models.CharField(blank=True, max_length=200, verbose_name='מחוז / איזור'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='division',
            field=models.CharField(blank=True, max_length=200, verbose_name='חטיבה'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_set',
            field=models.CharField(blank=True, max_length=200, verbose_name='ערכת ציוד'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='file_count',
            field=models.IntegerField(default=0, verbose_name='מספר קבצים'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='floor_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='קומה'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/images/', verbose_name='תמונה'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inspection_status',
            field=models.CharField(blank=True, choices=[('valid', 'תקין'), ('approaching', 'מתקרב'), ('expired', 'לא תקין'), ('none', 'ללא בדיקה')], default='none', max_length=20, verbose_name='סטטוס בדיקות'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='internal_serial_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='מספר סידורי פנימי'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='license_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='מספר רישיון / רישוי'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='max_allowed_pressure',
            field=models.CharField(blank=True, max_length=200, verbose_name='לחץ מירבי מותר'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='measurement_range',
            field=models.CharField(blank=True, max_length=200, verbose_name='טווח מדידה'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='measurement_resolution',
            field=models.CharField(blank=True, max_length=100, verbose_name='רזולוציית מדידה'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='יחידת מדידה'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='periodic_inspections',
            field=models.TextField(blank=True, verbose_name='בדיקות תקופתיות'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='production_line',
            field=models.CharField(blank=True, max_length=200, verbose_name='קו ייצור'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='project',
            field=models.CharField(blank=True, max_length=200, verbose_name='פרויקט'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, max_length=100, verbose_name='חדר'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='safe_working_load',
            field=models.CharField(blank=True, max_length=200, verbose_name='עומס עבודה בטוח'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service_company',
            field=models.CharField(blank=True, max_length=200, verbose_name='חברת שירות / קבלן'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='site_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='סטטוס אתר / סניף'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sub_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='תת מחלקה'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='super_domain',
            field=models.CharField(blank=True, max_length=200, verbose_name='תחום על'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='תגית'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='יחידה'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='פקיעת תוקף אחריות'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='wing',
            field=models.CharField(blank=True, max_length=200, verbose_name='אגף'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='yam_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='מספר יא״מ'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacity in tons/kg', max_digits=10, null=True, verbose_name='קיבולת'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='מחלקה'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, verbose_name='תאור'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='employer',
            field=models.CharField(blank=True, help_text='חברה', max_length=200, verbose_name='חברה'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='פריט ציוד'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('crane', 'Crane'), ('hoist', 'Hoist'), ('forklift', 'Forklift'), ('elevator', 'Elevator'), ('platform', 'Platform'), ('other', 'Other')], max_length=50, verbose_name='תחום ציוד'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters', max_digits=10, null=True, verbose_name='גובה'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inspector_name',
            field=models.CharField(blank=True, help_text='אחראי/ת', max_length=200, verbose_name='אחראי/ת'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך התקנה'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='בדיקה אחרונה'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location_details',
            field=models.TextField(blank=True, verbose_name='מיקום'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך ייצור'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacture_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='שנת ייצור'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='יצרן'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=200, verbose_name='דגם'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='next_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='בדיקה הבאה'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='הערה'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך רכישה'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='מספר סידורי יצרן'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='site_name',
            field=models.CharField(blank=True, help_text='אתר / סניף', max_length=200, verbose_name='אתר / סניף'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=20, verbose_name='סטטוס פריט ציוד'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='נפח'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='working_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Working pressure', max_digits=10, null=True, verbose_name='לחץ עבודה'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='workplace_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='מקום עבודה'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['inspection_status'], name='equipment_inspect_c26a17_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['employer'], name='equipment_employe_d5ffe4_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['site_name'], name='equipment_site_na_db40d3_idx'),
        ),
    ]
