# Generated by Django 4.2.9 on 2026-03-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_address_equipment_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('lifting_accessories', 'אביזרי הרמה'), ('no_inspection_required', 'לא חייב בבדיקה'), ('forklifts', 'מלגזות'), ('lifting_facilities', 'מתקני הרמה')], max_length=50, verbose_name='תחום ציוד'),
        ),
    ]
