# Generated by Django 4.2.9 on 2026-03-11 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0005_equipmentphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='כותרת')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('frequency', models.CharField(choices=[('daily', 'יומי'), ('weekly', 'שבועי'), ('monthly', 'חודשי'), ('quarterly', 'רבעוני'), ('semi_annual', 'חצי שנתי'), ('annual', 'שנתי'), ('custom', 'מותאם אישית')], max_length=20, verbose_name='תדירות')),
                ('custom_interval_days', models.PositiveIntegerField(blank=True, help_text='Number of days between tasks (for custom frequency)', null=True, verbose_name='מרווח ימים מותאם')),
                ('start_date', models.DateField(verbose_name='תאריך התחלה')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='תאריך סיום')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL, verbose_name='אחראי')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='equipment.equipment', verbose_name='ציוד')),
            ],
            options={
                'db_table': 'maintenance_schedules',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='כותרת')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('in_progress', 'בביצוע'), ('completed', 'הושלם'), ('overdue', 'באיחור'), ('cancelled', 'בוטל')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('priority', models.CharField(choices=[('low', 'נמוכה'), ('medium', 'בינונית'), ('high', 'גבוהה'), ('critical', 'קריטית')], default='medium', max_length=20, verbose_name='עדיפות')),
                ('due_date', models.DateField(verbose_name='תאריך יעד')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='תאריך השלמה')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='עלות')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='אחראי')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='equipment.equipment', verbose_name='ציוד')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maintenance.maintenanceschedule', verbose_name='לוח זמנים')),
            ],
            options={
                'db_table': 'maintenance_tasks',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='maintenance_status_d90cd5_idx'), models.Index(fields=['equipment', 'status'], name='maintenance_equipme_a245f1_idx')],
            },
        ),
    ]
