# Generated by Django 4.2.9 on 2026-01-16 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('manual', 'Manual'), ('certificate', 'Certificate'), ('inspection', 'Inspection Report'), ('warranty', 'Warranty'), ('maintenance', 'Maintenance Record'), ('photo', 'Photo'), ('drawing', 'Technical Drawing'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('description', models.TextField(blank=True)),
                ('document_date', models.DateField(blank=True, help_text='Document date or validity date', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date for certificates', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='equipment.equipment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['document_type'], name='documents_documen_fc21d0_idx'), models.Index(fields=['document_date'], name='documents_documen_718437_idx')],
            },
        ),
    ]
