# Generated by Django 4.2.9 on 2026-03-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.company', verbose_name='חברה'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='תפקיד'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='he', max_length=10, verbose_name='שפה'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
